version: 2
updates:
  - package-ecosystem: "mise"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "mise"
      include: "scope"
    labels:
      - "dependencies"
      - "mise"
    file-type: "config.toml"
    file-name: "dot_config/mise/config.toml" 
